name: Rumble Download (Callback)

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Rumble video URL'
        required: true
      callback_url:
        description: 'n8n callback URL'
        required: true
      tag:
        description: 'Correlation tag'
        required: false
        default: ''

jobs:
  dl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yt-dlp + ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3-pip jq
          pip3 install -U yt-dlp

      - name: Download video
        id: grab
        env:
          URL: ${{ github.event.inputs.url }}
          TAG: ${{ github.event.inputs.tag }}
        run: |
          mkdir -p out
          BASE="${TAG:-rumble}"
          yt-dlp --no-part --merge-output-format mp4 -f "bv*+ba/best" \
            -o "out/${BASE}_%(title).200B [%(id)s].%(ext)s" \
            --restrict-filenames --write-info-json --write-thumbnail \
            "$URL"
          FILE=$(ls -1t out/*.mp4 | head -n 1)
          echo "file=$FILE" >> $GITHUB_OUTPUT

      - name: Upload to transfer.sh
        id: up
        run: |
          FILE="${{ steps.grab.outputs.file }}"
          NAME="$(basename "$FILE")"
          URL=$(curl --silent --upload-file "$FILE" "https://transfer.sh/$NAME")
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "name=$NAME" >> $GITHUB_OUTPUT

      - name: Post callback to n8n
        env:
          CB: ${{ github.event.inputs.callback_url }}
          ORIG: ${{ github.event.inputs.url }}
          TAG: ${{ github.event.inputs.tag }}
        run: |
          curl -s -X POST "$CB" \
            -H 'Content-Type: application/json' \
            -d "$(jq -n \
                --arg file_url '${{ steps.up.outputs.url }}' \
                --arg file_name '${{ steps.up.outputs.name }}' \
                --arg rumble_url "$ORIG" \
                --arg tag "$TAG" \
                --arg html_run "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
                '{status:"ready", file_url:$file_url, file_name:$file_name, rumble_url:$rumble_url, tag:$tag, run_url:$html_run}')"
